### ISSUE TITLE
Xaero's Minimap/World Map

### ISSUE THREAD

**Issue by MoonlightSystem** [woodytexas/modpack-issues-suggestions#2]
People like me with ADHD and the like, struggle to keep track of where our bases and POI are, and a minimap/world map mod like Xaero's would help remedy that particular issue. Both mods are very configurable(e.g, disablng the minimap part, while keeping the waypoints and world map visible)

**Comment by woodiertexas** [comment]
Xaero's Minimap and World Map have been added in the v0.2.1-hotfix. It can be downloaded here: https://modrinth.com/modpack/vanilla++
